image:
  repository: fabian2001/carla-scheduler
  tag: "v1.6"
  pullPolicy: Always

env:
  - name: CARLA_POLICY
    value: /app/configs/carla_policy.yaml
  - name: CARLA_APPS
    value: /app/configs/apps.yaml
  - name: ARGO_TOKEN
    valueFrom:
      secretKeyRef:
        name: carla-argocd-token
        key: token
  - name: PYTHONWARNINGS
    value: "ignore:Unverified HTTPS request"

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

rbac:
  create: true
  namespace: carla

serviceAccount:
  create: true
  name: ""
  annotations: {}

secrets:
  createArgoToken: false
  argoToken: ""

argo:
  baseUrl: "https://argo-cd-argocd-server.argocd.svc.cluster.local"
  verifyTLS: false
  appNamespace: "argocd"

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

pdb:
  enabled: true
  minAvailable: 1
